AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS nginx proxy"
Parameters:
  VPCStackName:
    Description: Name of our VPC Stack
    Type: String
  DBStackName:
    Description: Name of our DB Stack
    Type: String
  AMI:
    Description: AMI ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
  InstanceType:
    Description: Instance Type
    Type: String
    Default: t3.micro
Resources:
  NginxInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for NginxInstance 
      VpcId:
        Fn::ImportValue:
          !Join [":", [!Ref "VPCStackName", "VPCId"]]
  SSMInstanceIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties: 
      Description: Ingress from NginxInstance
      GroupId:
        Fn::ImportValue:
          !Join [":", [!Ref "DBStackName", "DBInstanceSG"]]
      IpProtocol: tcp
      FromPort:
        Fn::ImportValue:
          !Join [":", [!Ref "DBStackName", "DBPort"]]
      ToPort:
        Fn::ImportValue:
          !Join [":", [!Ref "DBStackName", "DBPort"]]
      SourceSecurityGroupId: !Ref NginxInstanceSG
  NginxRDSProxy:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
      - !Ref NginxInstanceSG
      SubnetId:
        Fn::ImportValue: !Join [':', [!Ref 'VPCStackName', 'PublicSubnetOne']]
      KeyName: yet-dev-access
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            yum update -y
            yum install nginx nginx-mod-stream -y
            cat <<'EOF' >/usr/share/nginx/modules/rds.conf
            # Load the stream module
            stream {
              upstream database_server {
                  server ${Host}:${Port};
              }
              server {
                  listen ${Port};
                  proxy_pass database_server;
                  proxy_connect_timeout 10s;
                  proxy_timeout 60s;
                  proxy_buffer_size 16k;
              }
            }
            EOF
            systemctl start nginx
          - Port:
              Fn::ImportValue:
                !Join [":", [!Ref "DBStackName", "DBPort"]]
            Host:
              Fn::ImportValue:
                !Join [":", [!Ref "DBStackName", "DBEndpoint"]]
Outputs:
  ProxyPublicIp:
    Description: Public IP of Nginx Proxy 
    Value: !GetAtt NginxRDSProxy.PublicIp
  ProxySG:
    Description: SG group for Nginx Proxy
    Value: !Ref NginxInstanceSG
