name: Build AMI

# on:
#  push:
#    tags:
#      - 'v*.*.*' # Enforce Semantic Versioning
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of LRSQL to build"
        required: true

jobs:
  upload_dbfn:
    runs-on: ubuntu-latest
    # These permissions are needed by configure-aws-credentials in order
    # to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read  # required to checkout the code from the repo
    steps:
      - name: Install JQ
        run: apt update && apt install -y jq

      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Extract version
      # id: version
      # run: echo version="v0.7.11" >> $GITHUB_OUTPUT
      # run: echo version=${GITHUB_REF#refs\/tags\/} >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::376099832799:role/lrsql-imagebuilder-ghacti-BuildAMIGithubActionsRole-IHZUC98qYzfG
          role-duration-seconds: 900 # 15 min; minimal duration possible
          # aws-region: us-east-1

      - name: Trigger AMI Build 
        run: ./dev-resources/template/marketplace/trigger-update.sh -v ${{ github.event.inputs.version }} 
