name: Deps

on:
  push:
    branches:
      - '*'
jobs:
  deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup CI Environment
        uses: yetanalytics/action-setup-env@v2

      - name: Cache Deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Make a POM
        run: make clean pom.xml

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4

      - name: Review Dependencies
        uses: actions/dependency-review-action@v4
        with:
          base-ref: 'refs/heads/main'
          head-ref: ${{ github.ref }}

